export default function DataUse() {
  return <main className="mx-auto max-w-2xl space-y-6 px-5 py-12 text-base leading-7">
    <a href="/" className="text-[#315b7d] underline">Back to TripSync</a>
    <h1 className="text-3xl font-semibold">TripSync data use & terms</h1>
    <section className="space-y-3"><h2 className="text-xl font-semibold">AI itinerary generation</h2><p>Clicking Generate itinerary sends your travel questionnaire choices, selected attraction names, and organizer dinner decision to DeepSeek to generate a draft. Your name and email are not sent by this endpoint. The other travelers currently use simulated profiles. The website does not save these generated drafts to a database; they remain in the current page until you reload it. DeepSeek and the hosting provider process requests under their own policies.</p><p>AI drafts can contain mistakes. Restaurant lookup is a separate service; a generated plan does not mean current prices, opening hours, travel routes, or availability have been verified.</p><a href="https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html" className="underline">DeepSeek Privacy Policy</a></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Restaurant searches</h2><p>When live lookup is connected, requesting restaurant candidates sends the meal's search area, cuisine query, and selected price band to Google Maps Platform. The restaurant endpoint does not send your name or the group's full questionnaire. It does not persist restaurant results. Choices remain in this page's memory and are lost when you leave or reload it.</p><p>Opening a Google Maps link takes you to Google, where its own privacy policy applies. The website hosting platform may process request information to operate the service.</p><p>Google's handling of data is described in its <a href="https://policies.google.com/privacy" className="underline">Privacy Policy</a>.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Using the travel draft</h2><p>This is a coursework prototype. Travel times, schedules, and meal estimates are planning suggestions. Provider price bands and usual opening hours do not guarantee actual menu prices, future opening hours, seating, dietary suitability, or reservations. Confirm these with the venue before visiting or paying. Choosing a restaurant here does not reserve a table.</p><p>Google Maps content is subject to the <a href="https://policies.google.com/terms" className="underline">Google Terms of Service</a> and <a href="https://www.google.com/intl/en/help/terms_maps/" className="underline">Google Maps Additional Terms</a>.</p></section>
  </main>;
}
